/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovU0VNRVNURVIgNC9QV0wvTUFURVJJIGRhbiBBUEsvQmVsYWphciBBbmd1bGFyL1ByYWsxL2RlcGxveS1kZW1vL3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1NFTUVTVEVSIDQvUFdML01BVEVSSSBkYW4gQVBLL0JlbGFqYXIgQW5ndWxhci9QcmFrMS9kZXBsb3ktZGVtby9zcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
